### ISSUE TITLE
Rancher 2 Support

### ISSUE THREAD

**Issue by ballerabdude** [rancher/rancher-ecr-credentials#13]
Has anyone got this to work on rancher 2?

I am stuck here 
![image](https://user-images.githubusercontent.com/7660642/39305074-d1d7fe64-4929-11e8-972d-4b0cfcfa92f5.png)

**Comment by vincent99** [comment]
The catalog item is for 1.x.  k8s has its own built in support: https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry
