### ISSUE TITLE
Incomprensible documentation

### ISSUE THREAD

**Issue by francesco2013** [rancher/rancher-ecr-credentials#17]
This is not really an "issue" but from your documentation nothing is clear. At all. 

So I have AWS_KEY, AWS_SECRET and I know AWS_REGION for ECR. Now could you please tell me which ENV variables I have to give to the container in order to have once for all Rancher 2 pulling images from our repository on ECR ? What about network ports if needed ? 

You dont explain anything there is not even a screenshot of the Rancher 2.0 page where you setup the workload where you can see how is that made ? I am sorry but writing a document that would be humanly understandable was a real problem ?

Please be so kind to explain step by step how to do this and how to ensure that Rancher 2.0 will then be able to access our ECR repository. 

Thanks.

**Comment by vincent99** [comment]
This repo and service is for Rancher 1.x, not 2.0/kubernetes.  https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry
