### ISSUE TITLE
retry immediately after HTTP failure with exponential back-off 

### ISSUE THREAD

**Issue by wjimenez5271** [rancher/rancher-ecr-credentials#4]
currently client won't retry after a failed update attempt until next poll cycle which is 6 hours. We shouldn't wait this long if there was just a network interruption when we tried to make an HTTP call to either AWS or Rancher API.

**Comment by h2suzuki** [comment]
We actually observed this issue, so transient HTTP failures may be occurring sometimes in ECR.
The severity looks high.

**Comment by wjimenez5271** [comment]
@h2suzuki FYI this fix should be available in Rancher 1.6.13
